apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-backend-app
  labels:
    app: petstore-backend-app
    drift-severity: "low"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petstore-backend-app
  template:
    metadata:
      labels:
        app: petstore-backend-app
    spec:
      containers:
      - name: app
        image: nginx:1.20
        ports:
        - containerPort: 80
